services:
  mininet:
    build:
      dockerfile_inline: |
        FROM iwaseyusuke/mininet:ubuntu-22.04

        RUN apt-get update && \
            apt-get install -y tmux python3-pip && \
            pip3 install --no-cache-dir ryu && \
            apt-get clean && \
            sed -i '/class _AlreadyHandledResponse/,/^$/d' /usr/local/lib/python3.*/dist-packages/ryu/app/wsgi.py && \
            sed -i '/_AlreadyHandledResponse()/d' /usr/local/lib/python3.*/dist-packages/ryu/app/wsgi.py

    tty: true
    stdin_open: true
    privileged: true
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./src:/root/src
